### ISSUE TITLE
Memory management question for Repeater (timer stop just after the creation)

### ISSUE THREAD

**Issue by aarefin** [malcommac/Repeat#18]
Simple code in func application() of AppDelegate class:

```swift
let timer = Repeater(interval: .seconds(5), mode: .infinite) { _ in
  print("started")
}
timer.onStateChanged = { (timer,newState) in
  print(newState)
}
timer.start()
```

Output:

```
running
executing
idle/paused
```

**Comment by malcommac** [comment]
As any other object in Swift/ObjC environment your object is subject to the memory management rules. You need to retain your timer somewhere, otherwise `timer` property will be deallocated just after the creation.
