### ISSUE TITLE
Default branch is not develop

### ISSUE THREAD

**Issue by philium** [malcommac/Repeat#19]
It appears that PRs are merged into `develop`, but the default branch is `master`. Should the default branch [be changed](https://help.github.com/articles/setting-the-default-branch/) to `develop`?

**Comment by malcommac** [comment]
Hi, I'm using gitflow, so PRs are merged in `develop` until a new release is ready, then everything is merged into `master` and a new tagged build is set.
(I've made several typo fixes for readme directly on `master` and reported also on `develop` later).

**Comment by philium** [comment]
I understand that. I am very familiar with git flow.

My understanding is that by assigning `develop` as the default branch, `develop` would become the default base for future pull requests. It seems like that would take care of having to manually change the base of PRs from `master` (since that is set as the base by default) to `develop`. Does that make sense?

**Comment by malcommac** [comment]
Got it, you are right,I misunderstood.
Just set the default branch to`develop`.
Thank you @philium
