### ISSUE TITLE
Timer's require strong references

### ISSUE THREAD

**Issue by anthonycastelli** [malcommac/Repeat#21]
No matter what function I use, every times requires a strong reference in order to fire. 

Everything instantly deallocates itself if I dont have a strong reference. I'm creating multiple timers and dont want to have to declare a dozen variables to store all of these, thats just not practical. 

Looking at the tests, I should be able to do this, however, the same thing appears to happen here.
```swift
let timer = Repeater(interval: .seconds(1), mode: .infinite) { timer in
    print("Timer")
}
timer.start()
```

Did I miss something in the readme about this requiring a strong reference of itself to continuously fire, or is this a bug? Been wracking my head out for about 2 hours trying to figure out what the hell was going on. 

Thanks

**Comment by malcommac** [comment]
This is a memory management question; obviously you need to keep the timer alive as any other object, so strong reference is part of the game.
I've also added this stuff into the doc, even if its a general question more than a specific timer-related question.
