### ISSUE TITLE
How to create and run a timer when application is in background

### ISSUE THREAD

**Issue by thenappanz** [malcommac/Repeat#25]
Repeater.once function will trigger if the app is in the background or lock screen?

**Comment by malcommac** [comment]
Have you enabled Background Capabilities in your app?
What's you code?
Depending on what you are trying to accomplish timer could be or not a good idea; you have a finite amount of time to do some background stuff with your code so if you are using a timer to plan something longer you should change your approach and use something different (a push maybe?).

However, after enabling background fetch you can create your timer in function like as the example below; it works fine with my test project:

```swift
class AppDelegate: UIResponder, UIApplicationDelegate {
	private var timer: Repeater?
       private var bgTask: UIBackgroundTaskIdentifier?

       func applicationDidEnterBackground(_ application: UIApplication) {
		self.e = UIApplication.shared.beginBackgroundTask(withName: "prova", expirationHandler: {
			// do something to cleanup your stuff
			self.timer = nil
                        self. bgTask = UIBackgroundTaskInvalid
		})
		
		self.timer = Repeater.once(after: .seconds(4), { _ in
			// timer fired
		})
	}
}

```
