### ISSUE TITLE
Suggestion: decrease remaining iterations before notifying observers

### ISSUE THREAD

**Issue by ybeapps** [malcommac/Repeat#27]
Hi, Great Code - Solved my unfiring timer when user drag content (imagine a quiz without a timeout LOL)

Well, in "timeFired()" maybe it's better to update the state of the timer and then notify the observers?
because the observers might use the timer state to update UI, and if I check "remainingIterations" I'll get 1 - but it's 0... and the last iteration that my code excepts will never happen =]

**Comment by malcommac** [comment]
Nice suggetion @ybeapps . I've integrated it into 0.5.5 release.
